# Generated by Django 2.0.7 on 2018-09-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='fan_address',
            field=models.CharField(default='', max_length=200, verbose_name='还车地址'),
        ),
    ]
